name: Fetch and Save Invoices

on:
  workflow_dispatch:
    inputs:
      param1:
        description: 'Popis'
        required: false

jobs:
  fetch_and_save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Fetch invoices
        env:
          KEY: ${{ secrets.KEY }} # Predpokladám, že token je uložený ako GitHub Secret s názvom KEY
          EMAIL: ${{ secrets.EMAIL }} # Predpokladám, že e-mail je uložený ako GitHub Secret s názvom EMAIL
        run: |
          # Vytvoríme JSON objekt s dátami pre POST požiadavku
          data="{\"key\":\"${KEY}\",\"email\":\"${EMAIL}\"}"
          url_encoded_data=$(jq -c -r '@uri' <<< ${data})

          # Vytvoríme POST požiadavku na získanie tokenu
          token_response=$(curl -X GET "https://www.faktury-online.com/api/init?data=${url_encoded_data}" -c cookies.txt)
          cookie=$(cat cookies.txt)
          echo COOKIE: ${cookie}
          echo TOKEN RESPONSE: ${token_response}

          # Vytvoríme GET požiadavku na získanie faktúr s použitím získaného tokenu
          invoices_response=$(curl -X GET "https://www.faktury-online.com/api/list/created?data=${url_encoded_data}" -b "${cookie}" -v -i)
          echo ${invoices_response}

          # Uložíme odpoveď do súboru (príklad súboru: invoices.json)
          echo ${invoices_response} > invoices.json

      - name: Save file to repository
        uses: actions/upload-artifact@v2
        with:
          name: invoices  # Názov pre archív s faktúrami
          path: invoices.json

