name: Fetch and Save Invoices

on:
  workflow_dispatch:
    inputs:
      param1:
        description: 'Popis'
        required: false

jobs:
  fetch_and_save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Fetch invoices
        env:
          KEY: ${{ secrets.KEY }} # Predpokladám, že token je uložený ako GitHub Secret s názvom KEY
          EMAIL: ${{ secrets.EMAIL }} # Predpokladám, že e-mail je uložený ako GitHub Secret s názvom EMAIL
        run: |
          # Vytvoríme JSON objekt s dátami pre POST požiadavku
          data="{\"key\":\"${KEY}\",\"email\":\"${EMAIL}\"}"

          # Vytvoríme POST požiadavku na získanie tokenu
          token_response=$(curl -X POST -H "Content-Type: application/json" -d "${data}" "https://www.faktury-online.com/api/init")

          # Získame token z odpovede
          TOKEN=$(echo ${token_response} | jq -r '.token')

          # Vytvoríme GET požiadavku na získanie faktúr s použitím získaného tokenu
          invoices_response=$(curl -X GET "https://www.faktury-online.com/api/list/created?token=${TOKEN}")

          # Uložíme odpoveď do súboru (príklad súboru: invoices.json)
          echo ${invoices_response} > invoices.json
