name: Fetch and Save Invoices

on:
  pull:
    branches:
      - next # Keď pullneš zmey, pustí sa akcia

jobs:
  fetch_and_save:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch invoices
        env:
          KEY: ${{ secrets.KEY }} # Predpokladám, že token je uložený ako GitHub Secret s názvom KEY
          EMAIL: ${{ secrets.EMAIL }} # Predpokladám, že e-mail je uložený ako GitHub Secret s názvom EMAIL
        run: |
          # Vytvoríme požiadavku na získanie tokenu
          INIT_RESPONSE=$(curl -X GET "https://www.faktury-online.com/api/init?data={\"key\":\"${KEY}\",\"email\":\"${EMAIL}\"}")

          # Získame token z odpovede
          TOKEN=$(echo ${INIT_RESPONSE} | jq -r '.token')

          # Vytvoríme požiadavku na získanie faktúr s použitím získaného tokenu
          INVOICES_RESPONSE=$(curl -X GET "https://www.faktury-online.com/api/list/created?token=${TOKEN}")

          # Uložíme odpoveď do súboru (príklad súboru: invoices.json)
          echo ${INVOICES_RESPONSE} > invoices.json

          # Commitneme a pushneme súbor do GitHub-u
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add invoices.json
          git commit -m "New invoices"
          git push origin HEAD:main
